services:
  fcp-defra-id-stub:
    profiles: ["app"]
    build:
      context: .
      target: development
    ports:
      - '${FCP_DEFRA_ID_STUB_PORT:-3007}:${FCP_DEFRA_ID_STUB_PORT:-3007}'
    env_file:
      - path: .env
        required: false
    environment:
      PORT: ${FCP_DEFRA_ID_STUB_PORT:-3007}
      AWS_REGION: eu-west-2
      AWS_ENDPOINT_URL: http://floci:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_S3_ENABLED: ${FCP_DEFRA_ID_STUB_AWS_S3_ENABLED:-true}
      AWS_S3_BUCKET: fcp-defra-id-stub-data
      ENTRA_WELL_KNOWN_URL: https://login.microsoftonline.com/${ENTRA_TENANT_ID}/v2.0/.well-known/openid-configuration
      REDIS_HOST: redis
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
      - ./example.data.json:/data/example.data.json
    networks:
      - fcp-defra-id-stub
    depends_on:
      floci-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  floci:
    image: floci/floci:latest
    user: root # Required for S3
    ports:
      - '4566:4566'
    environment:
      FLOCI_HOSTNAME: floci
      FLOCI_DEFAULT_REGION: eu-west-2
      FLOCI_STORAGE_MODE: persistent
      FLOCI_STORAGE_PERSISTENT_PATH: /app/data
      FLOCI_STORAGE_SERVICES_S3_MODE: persistent
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - floci-data:/app/data
    networks:
      - fcp-defra-id-stub

  floci-init:
    image: amazon/aws-cli
    entrypoint: /bin/sh
    command: /setup/init.sh
    depends_on:
      floci:
        condition: service_started
    environment:
      AWS_ENDPOINT_URL: http://floci:4566
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - ./floci/init.sh:/setup/init.sh
    networks:
      - fcp-defra-id-stub

  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - fcp-defra-id-stub

networks:
  fcp-defra-id-stub:
    driver: bridge
    name: fcp-defra-id-stub

volumes:
  floci-data:
