services:
  fcp-defra-id-stub:
    build:
      context: .
      target: development
    environment:
      PORT: ${FCP_DEFRA_ID_STUB_PORT:-3007}
      AUTH_MODE: ${AUTH_MODE:-basic}
      AUTH_OVERRIDE: ${AUTH_OVERRIDE}
      AUTH_OVERRIDE_FILE: ${AUTH_OVERRIDE_FILE}
      AWS_REGION: eu-west-2
      AWS_ENDPOINT_URL: http://floci:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_S3_ENABLED: ${FCP_DEFRA_ID_STUB_AWS_S3_ENABLED:-true}
      AWS_S3_BUCKET: fcp-defra-id-stub-data
      ENTRA_ENABLED: ${ENTRA_ENABLED:-false}
      ENTRA_WELL_KNOWN_URL: https://login.microsoftonline.com/${ENTRA_TENANT_ID}/v2.0/.well-known/openid-configuration
      ENTRA_CLIENT_ID: ${ENTRA_CLIENT_ID}
      ENTRA_CLIENT_SECRET: ${ENTRA_CLIENT_SECRET}
      ENTRA_REDIRECT_URL: http://localhost:3007/auth/sign-in-oidc
      ENTRA_SIGN_OUT_REDIRECT_URL: http://localhost:3007/auth/sign-out-oidc
      REDIS_HOST: redis
      COOKIE_PASSWORD: this-is-a-secret-that-must-be-at-least-32-characters
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    depends_on:
      floci-init:
        condition: service_completed_successfully

  floci:
    image: hectorvent/floci:latest
    user: root # Required for S3
    environment:
      FLOCI_HOSTNAME: floci
      FLOCI_DEFAULT_REGION: eu-west-2
      FLOCI_STORAGE_MODE: persistent
      FLOCI_STORAGE_PERSISTENT_PATH: /app/data
      FLOCI_STORAGE_SERVICES_S3_MODE: persistent
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test

  floci-init:
    image: amazon/aws-cli
    entrypoint: /bin/sh
    command: /setup/init.sh
    depends_on:
      floci:
        condition: service_started
    environment:
      AWS_ENDPOINT_URL: http://floci:4566
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - ./floci/init.sh:/setup/init.sh

  redis:
    image: redis
