services:
  fcp-defra-id-stub:
    ports:
      - '${FCP_DEFRA_ID_STUB_PORT:-3007}:${FCP_DEFRA_ID_STUB_PORT:-3007}'
    networks:
      - fcp-defra-id-stub
    volumes:
      - ./example.data.json:/data/example.data.json

  floci:
    ports:
      - '4566:4566'
    volumes:
      - floci-data:/app/data
    networks:
      - fcp-defra-id-stub

  floci-init:
    networks:
      - fcp-defra-id-stub

  redis:
    networks:
      - fcp-defra-id-stub

networks:
  fcp-defra-id-stub:
    driver: bridge
    name: fcp-defra-id-stub

volumes:
  floci-data:
